{
 "title": "Rust Server Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "server",
    "label": "Rust Server",
    "query": "SHOW TAG VALUES WITH KEY=server"
   }
  ]
 },
 "panels": [
  { "title": "Server Averages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Frame Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "framerate",
     "query": "SELECT \"instant\" FROM \"framerate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "instant" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Frame Rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Frame Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "frametime",
     "select": [
      [
       { "params": [ "instant" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Frame Time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Player Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "players",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Connected" ], "type": "alias" }
      ],
      [
       { "params": [ "joining" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Joining" ], "type": "alias" }
      ],
      [
       { "params": [ "queued" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Queued" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "allocations" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Allocations" ], "type": "alias" }
      ],
      [
       { "params": [ "collections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Collections" ], "type": "alias" }
      ],
      [
       { "params": [ "gc" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Garbage" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Entities",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "entities",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Total Count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tasks",
     "select": [
      [
       { "params": [ "invoke_handler" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Invoke Handler" ], "type": "alias" }
      ],
      [
       { "params": [ "load_balancer" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Load Balancer" ], "type": "alias" }
      ],
      [
       { "params": [ "workshop_skins_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Skins Queue" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Plugin Hook Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_server - $tag_plugin",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "plugin" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "oxide_plugins",
     "select": [
      [
       { "params": [ "hookTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Average" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "connection_latency",
     "query": "SELECT mode(\"ping\") AS \"Common\", mean(\"ping\") AS \"Average\" FROM \"connection_latency\" WHERE (\"server\" = 'select tag value') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "ping" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       },
       { "params": [ "Common" ], "type": "alias" }
      ],
      [
       { "params": [ "ping" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Average" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "network",
     "select": [
      [
       { "params": [ "bytes_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1024 / 1024 * 8" ], "type": "math" },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1024 / 1024 * 8" ], "type": "math" },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "network_updates",
     "query": "SELECT sum(*) AS :field FROM \"network_updates\" WHERE (\"server\" =~ /$server$/) AND $timeFilter GROUP BY time($__interval), \"server\" fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "MessageType" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server - $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "SELECT mean(\"packet_loss\") AS \"Latency\" FROM \"connection_latency\" WHERE $timeFilter GROUP BY time($interval), \"ip\", \"steamid\" fill(none)",
     "select": [
      [
       { "params": [ "packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Packet Loss" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "Player Averages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Player FPS",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server - $tag_steamid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "steamid" ], "type": "tag" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "client_performance",
     "select": [
      [
       { "params": [ "fps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Player Memory",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "$tag_server - $tag_steamid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "steamid" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "client_performance",
     "select": [
      [
       { "params": [ "memory" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Player Latency",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server - $tag_steamid - $tag_ip",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "steamid" ], "type": "tag" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "connection_latency",
     "query": "SELECT mean(\"ping\") AS \"Latency\" FROM \"connection_latency\" WHERE $timeFilter GROUP BY time($interval), \"ip\", \"steamid\" fill(none)",
     "select": [
      [
       { "params": [ "ping" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Latency" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Player Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server - $tag_steamid - $tag_ip",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "steamid" ], "type": "tag" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "connection_latency",
     "query": "SELECT mean(\"packet_loss\") AS \"Latency\" FROM \"connection_latency\" WHERE $timeFilter GROUP BY time($interval), \"ip\", \"steamid\" fill(none)",
     "select": [
      [
       { "params": [ "packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Packet Loss" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  }
 ]
}