{
 "title": "Rust Process Manager",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "server",
    "label": "Rust Server",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: v.defaultBucket,\r\n  tag: \"server\",\r\n  predicate: (r) => true,\r\n  start: -inf\r\n)"
   }
  ]
 },
 "panels": [
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Frame Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "FPS" } },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "framerate",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"framerate\")\r\n  |> filter(fn: (r) => r._field == \"instant\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> group(columns: [\"server\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "instant" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Frame Rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Frame Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "frametime",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"frametime\")\r\n  |> filter(fn: (r) => r._field == \"instant\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> group(columns: [\"server\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "instant" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Frame Time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Player Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "players",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"players\")\r\n  |> filter(fn: (r) => r._field == \"count\" or r._field == \"joining\" or r._field == \"queued\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> group(columns: [\"server\", \"_field\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Connected" ], "type": "alias" }
      ],
      [
       { "params": [ "joining" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Joining" ], "type": "alias" }
      ],
      [
       { "params": [ "queued" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Queued" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "memory",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"memory\")\r\n  |> filter(fn: (r) => r._field == \"allocations\" or r._field == \"collections\" or r._field == \"used\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> group(columns: [\"server\", \"_field\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "allocations" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Allocations" ], "type": "alias" }
      ],
      [
       { "params": [ "collections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Collections" ], "type": "alias" }
      ],
      [
       { "params": [ "gc" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Garbage" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Entities",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "entities",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"entities\")\r\n  |> filter(fn: (r) => r._field == \"count\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> group(columns: [\"server\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Total Count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "tasks",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"tasks\")\r\n  |> filter(fn: (r) => r._field == \"invoke_handler\" or r._field == \"load_balancer\" or r._field == \"workshop_skins_queue\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "invoke_handler" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Invoke Handler" ], "type": "alias" }
      ],
      [
       { "params": [ "load_balancer" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Load Balancer" ], "type": "alias" }
      ],
      [
       { "params": [ "workshop_skins_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Skins Queue" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Plugin Hook Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_server - $tag_plugin",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "plugin" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "oxide_plugins",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"oxide_plugins\")\r\n  |> filter(fn: (r) => r._field == \"hookTime\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "hookTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Average" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_server - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "connection_latency",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"connection_latency\")\r\n  |> filter(fn: (r) => r._field == \"ping\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> group(columns: [\"server\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)",
     "select": [
      [
       { "params": [ "ping" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       },
       { "params": [ "Common" ], "type": "alias" }
      ],
      [
       { "params": [ "ping" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Average" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "query": "  from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"connection_latency\")\r\n  |> filter(fn: (r) => r._field == \"ping\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> group(columns: [\"server\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mode, createEmpty: true)"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "$tag_server - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"network\")\r\n  |> filter(fn: (r) => r._field == \"bytes_received\" or r._field == \"bytes_sent\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> group(columns: [\"server\", \"_field\"], mode: \"by\")\r\n  |> map(fn: (r) => ({ r with _value: r._value * 8 }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "bytes_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1024 / 1024 * 8" ], "type": "math" },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1024 / 1024 * 8" ], "type": "math" },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "network_updates",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"network_updates\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "MessageType" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server - $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"network\")\r\n  |> filter(fn: (r) => r._field == \"packet_loss\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> group(columns: [\"server\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Packet Loss" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "Players", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Player FPS",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "FPS" } },
   "targets": [
    {
     "alias": "$tag_server - $tag_steamid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "steamid" ], "type": "tag" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "client_performance",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"client_performance\")\r\n  |> filter(fn: (r) => r._field == \"fps\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> group(columns: [\"server\", \"steamid\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "fps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Player Memory",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "$tag_server - $tag_steamid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "steamid" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "client_performance",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"client_performance\")\r\n  |> filter(fn: (r) => r._field == \"memory\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> group(columns: [\"server\", \"steamid\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "memory" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Player Latency",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_server - $tag_steamid - $tag_ip",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "steamid" ], "type": "tag" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "connection_latency",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"connection_latency\")\r\n  |> filter(fn: (r) => r._field == \"ping\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> group(columns: [\"server\", \"steamid\", \"ip\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "ping" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Latency" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Player Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server - $tag_steamid - $tag_ip",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "steamid" ], "type": "tag" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "connection_latency",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"connection_latency\")\r\n  |> filter(fn: (r) => r._field == \"packet_loss\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> group(columns: [\"server\", \"steamid\", \"ip\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Packet Loss" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  }
 ]
}