{
 "title": "RustServerMetrics-QuestDB-GrafanaDashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "postgres" },
   {
    "name": "server",
    "label": "Rust Server",
    "query": "SELECT DISTINCT(server) from 'framerate';"
   }
  ]
 },
 "panels": [
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Frame Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "FPS" } },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "framerate",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"framerate\")\r\n  |> filter(fn: (r) => r._field == \"instant\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> group(columns: [\"server\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "rawSql": "SELECT\n  timestamp as time,\n  server,\n  avg(instant)\nFROM framerate\nWHERE $__timeFilter(timestamp)\nAND server IN (${server})\nSAMPLE BY $__interval\n",
     "tags": [
      { "key": "server", "operator": "=~", "value": "/$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Frame Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "frametime",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"frametime\")\r\n  |> filter(fn: (r) => r._field == \"instant\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> group(columns: [\"server\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "rawSql": "SELECT\n  timestamp as time,\n  server,\n  avg(instant)\nFROM frametime\nWHERE $__timeFilter(timestamp)\nAND server IN (${server})\nSAMPLE BY $__interval\n",
     "tags": [
      { "key": "server", "operator": "=~", "value": "/$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Player Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "players",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"players\")\r\n  |> filter(fn: (r) => r._field == \"count\" or r._field == \"joining\" or r._field == \"queued\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> group(columns: [\"server\", \"_field\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "rawSql": "SELECT\n  timestamp as time,\n  server,\n  avg(count) as count,\n  avg(joining) as joining,\n  avg(queued) as queued\nFROM players\nWHERE $__timeFilter(timestamp)\nAND server IN (${server})\nSAMPLE BY $__interval\n",
     "tags": [
      { "key": "server", "operator": "=~", "value": "/$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "memory",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"memory\")\r\n  |> filter(fn: (r) => r._field == \"allocations\" or r._field == \"collections\" or r._field == \"used\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> group(columns: [\"server\", \"_field\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "rawSql": "SELECT\n  timestamp as time,\n  server,\n  avg(used) as used,\n  avg(collections) as collections,\n  avg(allocations) as allocations\nFROM memory\nWHERE $__timeFilter(timestamp)\nAND server IN (${server})\nSAMPLE BY $__interval",
     "tags": [
      { "key": "server", "operator": "=~", "value": "/$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Entities",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "entities",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"entities\")\r\n  |> filter(fn: (r) => r._field == \"count\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> group(columns: [\"server\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "rawSql": "SELECT\n  timestamp as time,\n  server,\n  avg(count) as count\nFROM entities\nWHERE $__timeFilter(timestamp)\nAND server IN (${server})\nSAMPLE BY $__interval",
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "tasks",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"tasks\")\r\n  |> filter(fn: (r) => r._field == \"invoke_handler\" or r._field == \"load_balancer\" or r._field == \"workshop_skins_queue\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "rawSql": "SELECT\n  timestamp as time,\n  server,\n  avg(load_balancer) as load_balancer,\n  avg(invoke_handler) as invoke_handler,\n  avg(workshop_skins_queue) as workshop_skins_queue\nFROM tasks\nWHERE $__timeFilter(timestamp)\nAND server IN (${server})\nSAMPLE BY $__interval",
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Plugin Hook Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_server - $tag_plugin",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "plugin" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "oxide_plugins",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"oxide_plugins\")\r\n  |> filter(fn: (r) => r._field == \"hookTime\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "rawSql": "SELECT\n  timestamp as time,\n  server,\n  plugin,\n  avg(hookTime) as hookTime\nFROM oxide_plugins\nWHERE $__timeFilter(timestamp)\nAND server IN (${server})\nSAMPLE BY $__interval",
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_server - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "connection_latency",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"connection_latency\")\r\n  |> filter(fn: (r) => r._field == \"ping\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> group(columns: [\"server\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)",
     "rawSql": "SELECT\n  timestamp as time,\n  server,\n  avg(ping) as ping\nFROM connection_latency\nWHERE $__timeFilter(timestamp)\nAND server IN (${server})\nSAMPLE BY $__interval",
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "$tag_server - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"network\")\r\n  |> filter(fn: (r) => r._field == \"bytes_received\" or r._field == \"bytes_sent\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> group(columns: [\"server\", \"_field\"], mode: \"by\")\r\n  |> map(fn: (r) => ({ r with _value: r._value * 8 }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "rawSql": "SELECT\n  timestamp as time,\n  server,\n  avg(bytes_sent) as Tx,\n  avg(bytes_received) as Rx\nFROM network\nWHERE $__timeFilter(timestamp)\nAND server IN (${server})\nSAMPLE BY $__interval",
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "network_updates",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"network_updates\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum)",
     "rawSql": "SELECT\n  timestamp as time,\n  server,\n  sum(\"0\") as \"0\",\n  sum(Welcome) as Welcome,\n  sum(Auth) as Auth,\n  sum(Approved) as Approved,\n  sum(Ready) as Ready,\n  sum(Entities) as Entities,\n  sum(EntityDestroy) as EntityDestroy,\n  sum(GroupChange) as GroupChange,\n  sum(GroupDestroy) as GroupDestroy,\n  sum(RPCMessage) as RPCMessage,\n  sum(EntityPosition) as EntityPosition,\n  sum(ConsoleMessage) as ConsoleMessage,\n  sum(ConsoleCommand) as ConsoleCommand,\n  sum(Effect) as Effect,\n  sum(DisconnectReason) as DisconnectReason,\n  sum(Tick) as Tick,\n  sum(Message) as Message,\n  sum(RequestUserInformation) as RequestUserInformation,\n  sum(GiveUserInformation) as GiveUserInformation,\n  sum(GroupEnter) as GroupEnter,\n  sum(GroupLeave) as GroupLeave,\n  sum(VoiceData) as VoiceData,\n  sum(EAC) as EAC,\n  sum(EntityFlags) as EntityFlags,\n  sum(World) as World,\n  sum(ConsoleReplicatedVars) as ConsoleReplicatedVars\nFROM network_updates\nWHERE $__timeFilter(timestamp)\nAND server IN (${server})\nSAMPLE BY $__interval",
     "tags": [
      { "key": "server", "operator": "=~", "value": "/$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server - $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"network\")\r\n  |> filter(fn: (r) => r._field == \"packet_loss\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> group(columns: [\"server\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "rawSql": "SELECT\n  timestamp as time,\n  server,\n  sum(packet_loss) as packet_loss\nFROM network\nWHERE $__timeFilter(timestamp)\nAND server IN (${server})\nSAMPLE BY $__interval",
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "Players", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Player FPS",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "FPS" } },
   "targets": [
    {
     "alias": "$tag_server - $tag_steamid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "steamid" ], "type": "tag" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "client_performance",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"client_performance\")\r\n  |> filter(fn: (r) => r._field == \"fps\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> group(columns: [\"server\", \"steamid\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "rawSql": "SELECT\n  timestamp as time,\n  server,\n  steamid,\n  avg(fps)\nFROM client_performance\nWHERE $__timeFilter(timestamp)\nAND server IN (${server})\nSAMPLE BY $__interval",
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Player Memory",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "$tag_server - $tag_steamid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "steamid" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "client_performance",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"client_performance\")\r\n  |> filter(fn: (r) => r._field == \"memory\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> group(columns: [\"server\", \"steamid\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "rawSql": "SELECT\n  timestamp as time,\n  server,\n  steamid,\n  avg(memory)\nFROM client_performance\nWHERE $__timeFilter(timestamp)\nAND server IN (${server})\nSAMPLE BY $__interval",
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Player Latency",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_server - $tag_steamid - $tag_ip",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "steamid" ], "type": "tag" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "connection_latency",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"connection_latency\")\r\n  |> filter(fn: (r) => r._field == \"ping\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> group(columns: [\"server\", \"steamid\", \"ip\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "rawSql": "SELECT\n  timestamp as time,\n  server,\n  steamid,\n  ip,\n  avg(ping)\nFROM connection_latency\nWHERE $__timeFilter(timestamp)\nAND server IN (${server})\nSAMPLE BY $__interval",
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Player Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server - $tag_steamid - $tag_ip",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "steamid" ], "type": "tag" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "connection_latency",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"connection_latency\")\r\n  |> filter(fn: (r) => r._field == \"packet_loss\")\r\n  |> filter(fn: (r) => contains(value: r.server, set: ${server:json}))\r\n  |> group(columns: [\"server\", \"steamid\", \"ip\"], mode: \"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "rawSql": "SELECT\n  timestamp as time,\n  server,\n  steamid,\n  ip,\n  avg(packet_loss)\nFROM connection_latency\nWHERE $__timeFilter(timestamp)\nAND server IN (${server})\nSAMPLE BY $__interval",
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  }
 ]
}